name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create Virtual Environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Check Python Version in venv
        run: python --version
      - name: Check pip Version in venv
        run: pip --version
      - name: Install Cython
        run: |
          source .venv/bin/activate
          pip install Cython
      - name: Check Cython Version
        run: |
          source .venv/bin/activate
          python -c "import Cython; print(Cython.__version__)"
      - name: Install Dependencies
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --no-cache-dir --prefer-binary flake8 pytest docker-compose
          if [ -f requirements.txt ]; then
            python -m pip install --no-cache-dir --prefer-binary -r requirements.txt
          fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F70,F72,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-line-length=127 --statistics
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          rm get-docker.sh
          sudo usermod -aG docker $USER
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Start Kafka Broker
        run: |
          docker-compose up -d
          echo "Docker Compose started"
          docker ps -a
          docker inspect kafka-broker # Log container details
      - name: Run Unit Tests with pytest
        run: |
          pytest -v ./tests/unit
      - name: Run Integration Tests with pytest
        run: |
          pytest -v ./tests/integration
      - name: Tear down Docker Compose
        if: always()
        run: |
          docker-compose down
          echo "Docker Compose stopped"
